// Lexique IA, vague 9, lot T (technique). Format identique à lexique/terms.js, sans `num`.
// imagineForm : forme de l'« Imagine » (content/dico/univers.md, section « Les formes de l'Imagine »).
// Faits et chiffres relevés le 2 octobre 2026 sur les pages citées dans `sources`.
module.exports = [
  {
    id: 'position',
    status: 'live',
    title: 'Encodage positionnel',
    en: 'Positional encoding',
    aliases: ['positional encoding', 'positional embedding', 'position embedding', 'RoPE', 'rotary position embedding', 'ALiBi', 'NoPE', 'YaRN', 'context extension'],
    aliasesFr: ['encodage de position', 'position des tokens', 'extension de contexte'],
    jargon: [
      {say: 'RoPE', means: "rotary position embedding, la méthode publiée en avril 2021 qui code la place d'un token en faisant tourner ses vecteurs d'un angle qui grandit avec sa position"},
      {say: 'rope_theta', means: "le réglage, dans la configuration d'un modèle, qui fixe la vitesse de l'aiguille la plus lente de RoPE ; il vaut 1 000 000 chez Qwen3"},
      {say: 'YaRN', means: "Yet another RoPE extensioN, une recette d'août 2023 pour faire lire à un modèle des textes plus longs que ceux de son entraînement"},
      {say: 'NoPE', means: "no positional encoding, des couches d'attention qui ne reçoivent aucune information de position, comme une partie de celles de Llama 4"},
    ],
    cat: 'fondations',
    links: ['auto-attention', 'transformer', 'embedding', 'kv-cache', 'mythe-lit-mot-par-mot', 'architectures-hybrides'],
    short: "L'encodage positionnel est l'information qu'un transformer ajoute à chaque token pour indiquer sa place dans le texte, parce que l'attention, seule, ne voit pas l'ordre des mots.",
    image: "Verse sur la table de mixage tous les samples d'un morceau sans leur minutage, et personne au studio ne saurait plus dire si le refrain venait avant ou après le couplet. L'encodage positionnel est le timecode gravé sur chaque sample, qui lui rend sa place dans le morceau. L'image triche sur la forme de ce timecode, qui n'est pas un numéro qu'on lit mais une série d'angles, et le modèle s'en sert surtout pour mesurer l'écart entre deux samples.",
    imagineForm: 'A',
    imagine: "Dans Qwen3-8B, publié par Alibaba en avril 2025, la place de chaque token est codée par 64 aiguilles qui tournent chacune à sa vitesse, d'un cran à chaque token. Si le modèle lisait un token par seconde, la plus rapide ferait un tour toutes les 6,3 secondes et la plus lente un tour en 58 jours et demi. Sur toute la fenêtre native du modèle, 32 768 tokens, soit neuf heures de lecture, cette dernière aiguille n'avance que de 2 degrés.",
    full: [
      "L'auto-attention compare chaque token aux autres sans rien savoir de leur place, et, sans autre indice, « le chien mord le facteur » et « le facteur mord le chien » lui apporteraient les mêmes mots. Les auteurs du transformer posent le problème dès juin 2017, en notant que leur modèle, sans récurrence ni convolution, doit recevoir de l'extérieur la position des tokens. Ils ajoutent à l'embedding de chaque token une signature faite d'ondes de longueurs différentes, de 2π à 10 000 fois 2π positions, et constatent qu'une version apprise donne des résultats presque identiques.",
      "La version apprise a pourtant une limite très concrète. GPT-2 apprenait une ligne de table par position, 1 024 en tout, et un 1 025e token n'y aurait trouvé aucune ligne. En avril 2021, Jianlin Su et ses coauteurs publient RoPE, qui fait tourner les vecteurs comparés par l'attention d'un angle proportionnel à leur place, si bien que le score entre deux tokens ne dépend plus que de leur écart. Ce sont ses aiguilles qui tournent dans Qwen3. ALiBi, publié en août de la même année, retire des points au score à mesure que la distance grandit, et un modèle entraîné sur 1 024 tokens en lisait ainsi 2 048.",
      "Une position jamais vue pendant l'entraînement désoriente le modèle, et l'allongement des fenêtres passe par là. En juin 2023, des chercheurs de Meta ont porté la fenêtre de LLaMA à 32 768 tokens en moins de 1 000 pas d'entraînement. Leur méthode resserre les positions pour qu'elles retombent dans la plage connue, au lieu de laisser les aiguilles tourner vers des angles inédits. YaRN, publié en août, affine cette recette, et Qwen3 s'en sert pour passer de 32 768 à 131 072 tokens.",
      "En avril 2025, Meta a même retiré tout encodage de position d'une partie des couches de Llama 4, une architecture qu'il appelle iRoPE, pour viser une fenêtre de 10 millions de tokens avec Llama 4 Scout. L'idée s'appuie sur une étude de mars 2022, selon laquelle un modèle qui ne regarde que les tokens précédents finit par déduire leur place sans aide, en somme en comptant combien il en a derrière lui.",
    ],
    office: [
      {who: 'q', text: "Notre Qwen3 installé en interne annonce 32 768 tokens. On peut lui confier un dossier de 100 000 ?"},
      {who: 'a', text: "Oui, en activant YaRN avec un facteur 4, qui le mène à 131 072 tokens. Alibaba conseille toutefois de ne pas le laisser allumé si tes textes restent sous les 32 768 tokens, car la version courante, à facteur fixe, peut dégrader les réponses sur les textes courts."},
    ],
    avoid: "« Le modèle sait où est chaque mot parce qu'il lit la phrase dans l'ordre. » Le transformer traite tous les tokens en même temps, et c'est l'encodage positionnel, ajouté à l'entrée ou appliqué dans chaque calcul d'attention, qui lui fournit l'ordre. Sans lui, il ne reste que le masque qui cache les tokens suivants pour laisser deviner une place.",
    video: null,
    sources: [
      {label: "Qwen, fichier config.json de Qwen3-8B sur Hugging Face (head_dim 128, rope_theta 1000000), consulté le 2 octobre 2026. Calcul de l'Imagine : 128 / 2 = 64 fréquences ; la plus rapide tourne d'un radian par token, soit un tour en 2π = 6,28 tokens ; la plus lente vaut 1 000 000^(-126/128) radian par token, soit un tour en 5 063 256 tokens, 58,6 jours à un token par seconde ; sur 32 768 tokens (9,1 heures), elle tourne de 360 × 32 768 / 5 063 256 = 2,3 degrés", url: 'https://huggingface.co/Qwen/Qwen3-8B/blob/main/config.json'},
      {label: "Qwen, fiche de Qwen3-8B sur Hugging Face, consultée le 2 octobre 2026 (32 768 tokens en natif, 131 072 avec YaRN, facteur 4 ; YaRN statique « potentially impacting performance on shorter texts », à n'activer que pour les longs contextes)", url: 'https://huggingface.co/Qwen/Qwen3-8B'},
      {label: "Wikipédia, Qwen (famille Qwen3 publiée le 28 avril 2025), consulté le 2 octobre 2026", url: 'https://en.wikipedia.org/wiki/Qwen'},
      {label: "Vaswani et al. (Google), Attention Is All You Need, juin 2017, section 3.5 (« Since our model contains no recurrence and no convolution... we must inject some information about the relative or absolute position » ; longueurs d'onde de 2π à 10000 · 2π ; version apprise aux résultats « nearly identical »)", url: 'https://arxiv.org/abs/1706.03762'},
      {label: "OpenAI, fichier config.json de GPT-2 sur Hugging Face (n_positions 1024), consulté le 2 octobre 2026 ; dans l'implémentation de Hugging Face, la position passe par une table apprise de cette taille (nn.Embedding(config.max_position_embeddings, ...))", url: 'https://huggingface.co/openai-community/gpt2/blob/main/config.json'},
      {label: "Su et al., RoFormer: Enhanced Transformer with Rotary Position Embedding, 20 avril 2021 (RoPE code la position absolue par une rotation et fait apparaître la position relative dans l'attention)", url: 'https://arxiv.org/abs/2104.09864'},
      {label: "Press, Smith et Lewis, Train Short, Test Long: Attention with Linear Biases Enables Input Length Extrapolation, 27 août 2021 (ALiBi pénalise le score d'attention proportionnellement à la distance ; entraîné sur 1 024 tokens, extrapole à 2 048)", url: 'https://arxiv.org/abs/2108.12409'},
      {label: "Chen et al. (Meta), Extending Context Window of Large Language Models via Positional Interpolation, 27 juin 2023 (LLaMA étendu jusqu'à 32 768 tokens en moins de 1 000 pas, positions réduites pour rester dans la fenêtre d'origine)", url: 'https://arxiv.org/abs/2306.15595'},
      {label: "Peng et al., YaRN: Efficient Context Window Extension of Large Language Models, 31 août 2023", url: 'https://arxiv.org/abs/2309.00071'},
      {label: "Meta, The Llama 4 herd, 5 avril 2025 (« interleaved attention layers without positional embeddings », architecture iRoPE ; Llama 4 Scout passe de 128 000 tokens chez Llama 3 à 10 millions)", url: 'https://ai.meta.com/blog/llama-4-multimodal-intelligence/'},
      {label: "Haviv et al., Transformer Language Models without Positional Encodings Still Learn Positional Information, 30 mars 2022 (sans encodage, un modèle causal acquiert une notion implicite de position absolue, sans doute en comptant les tokens qui le précèdent)", url: 'https://arxiv.org/abs/2203.16634'},
    ],
  },
  {
    id: 'architectures-hybrides',
    status: 'live',
    title: 'Architectures hybrides',
    en: 'Hybrid architectures',
    aliases: ['hybrid architecture', 'hybrid model', 'hybrid attention', 'linear attention', 'state space model', 'SSM', 'Mamba', 'Gated DeltaNet', 'Jamba', 'Kimi Linear'],
    aliasesFr: ['modèle hybride', 'attention hybride', 'attention linéaire', "modèle à espace d'états"],
    jargon: [
      {say: 'SSM', means: "state space model, modèle à espace d'états, une famille de couches récurrentes dont Mamba est la plus connue"},
      {say: 'linear attention', means: "l'attention linéaire, dont le coût grandit comme la longueur du texte et non comme son carré, parce qu'elle tient un résumé au lieu de tout relire"},
      {say: 'Gated DeltaNet', means: "la couche récurrente présentée en décembre 2024 par des chercheurs du MIT et de NVIDIA, qui efface ou corrige sa mémoire de façon ciblée ; c'est celle de Qwen3.5"},
      {say: '3:1', means: "trois couches récurrentes pour une couche d'attention complète, le dosage de Kimi Linear et de Qwen3.5"},
    ],
    cat: 'fondations',
    links: ['transformer', 'auto-attention', 'moe', 'position', 'fenetre-de-contexte', 'latence-vs-debit'],
    short: "Une architecture hybride mêle dans un même modèle des couches d'attention, qui relisent tout le texte, et des couches récurrentes, qui le résument dans une mémoire de taille fixe.",
    image: "Trois musiciens sur quatre jouent désormais de mémoire, avec pour seule aide un carnet de taille fixe qu'ils raturent et complètent à chaque mesure, et le quatrième garde toute la bande dans son casque pour retrouver une note précise jouée une heure plus tôt. L'architecture hybride organise ce partage entre couches récurrentes et couches d'attention. L'image triche sur le carnet, qui ne contient pas de notes lisibles mais un tableau de nombres remanié à chaque token.",
    imagineForm: 'D',
    imagine: "« Le dossier remplit les 262 144 tokens de la fenêtre ; combien de mémoire faut-il aux 45 couches Gated DeltaNet de Qwen3.5 pour le garder ? », demande une développeuse à son équipe. « Environ 190 Mo, autant que pour une seule phrase, et c'est aux 15 couches d'attention qu'il faut 8 Go de cache. »",
    full: [
      "L'attention complète a un défaut qui grandit avec le texte, puisque chaque nouveau token doit relire tout ce qui le devance et que le KV cache s'allonge d'autant. Les couches récurrentes reprennent l'idée des réseaux d'avant 2017, qui résumaient leur lecture au fil de l'eau dans une mémoire, l'état, dont la taille ne change pas, qu'on ait lu dix tokens ou un million. En décembre 2023, Albert Gu et Tri Dao publient Mamba, une couche de ce type qui choisit ce qu'elle garde selon le token lu, avec un débit annoncé cinq fois supérieur à celui d'un transformer.",
      "Ce résumé se paie en détails. En février 2024, des chercheurs de Harvard donnent à des modèles pré-entraînés un annuaire inventé, aux lignes du type « John Powell: 609-3237777 », puis demandent le numéro d'un nom tiré au hasard. Dès 70 noms, le plus petit transformer testé, 410 millions de paramètres, fait mieux que le plus gros Mamba, près de sept fois plus grand, parce que l'annuaire ne tient plus dans son état.",
      "D'où l'idée de garder un peu d'attention pour retrouver les détails et de confier le reste à des couches récurrentes. Jamba, sorti par AI21 Labs en mars 2024, place une couche d'attention pour sept couches Mamba et divise par huit son KV cache. En octobre 2025, Moonshot AI publie Kimi Linear, trois couches récurrentes pour une d'attention, avec jusqu'à 75 % de cache en moins et un décodage jusqu'à six fois plus rapide sur un million de tokens.",
      "Tout le monde n'en est pas convaincu. MiniMax avait bâti M1, en juin 2025, sur une attention hybride, puis est revenu à l'attention complète pour M2. Fin octobre 2025, ses ingénieurs ont expliqué qu'à grande échelle, la version hybride montrait de nets déficits sur les raisonnements qui enchaînent plusieurs indices. Ils prédisaient pourtant que les avantages des attentions économes apparaîtraient peu à peu, à mesure que la puissance des GPU progresserait moins vite que la longueur des textes.",
    ],
    then: "En 2024, Jamba faisait figure d'exception parmi des modèles presque tous bâtis sur l'attention complète. En février 2026, Alibaba a passé toute sa famille Qwen3.5 à l'architecture hybride, de la version de 0,8 milliard de paramètres à celle de 397 milliards, avec une couche d'attention pour trois couches Gated DeltaNet.",
    office: [
      {who: 'q', text: "Un modèle hybride, ça change quoi pour notre agent qui lit des dépôts de code entiers ?"},
      {who: 'a', text: "Surtout la mémoire et la vitesse quand le contexte s'allonge, et IBM annonce plus de 70 % de mémoire en moins sur les longs textes avec Granite 4.0. Vérifie quand même sur tes propres dépôts qu'il retrouve un détail précis enfoui au milieu, puisque c'est là que les couches récurrentes cèdent les premières."},
    ],
    avoid: "« Mamba a remplacé le transformer. » Jamba, Kimi Linear et Qwen3.5 gardent tous des couches d'attention complète, d'une sur huit à une sur quatre, justement pour retrouver les détails que la mémoire de taille fixe laisse filer. MiniMax est même revenu à l'attention complète pour M2.",
    video: null,
    sources: [
      {label: "Qwen, fichier config.json de Qwen3.5-397B-A17B sur Hugging Face, consulté le 2 octobre 2026 (60 couches, dont 45 linear_attention et 15 full_attention ; 2 têtes de clés et valeurs de 256 dimensions ; 64 têtes Gated DeltaNet de 128 × 128 ; état en float32 ; fenêtre de 262 144 tokens). Calculs de l'Imagine : cache des 15 couches d'attention = 15 × 2 × 2 × 256 × 2 octets = 30 720 octets par token, soit 8,05 Go à 262 144 tokens ; état des 45 couches = 45 × 64 × 128 × 128 × 4 octets = 189 Mo, quelle que soit la longueur", url: 'https://huggingface.co/Qwen/Qwen3.5-397B-A17B/blob/main/config.json'},
      {label: "Qwen, fiche de Qwen3.5-397B-A17B sur Hugging Face, consultée le 2 octobre 2026 (« Hidden Layout: 15 * (3 * (Gated DeltaNet -> MoE) -> 1 * (Gated Attention -> MoE)) » ; 262 144 tokens en natif)", url: 'https://huggingface.co/Qwen/Qwen3.5-397B-A17B'},
      {label: "Qwen, collection Qwen3.5 sur Hugging Face, consultée le 2 octobre 2026 (de Qwen3.5-0.8B à Qwen3.5-397B-A17B ; les configurations de 0.8B, 27B, 122B-A10B et 397B-A17B ont toutes une couche full_attention pour trois linear_attention)", url: 'https://huggingface.co/collections/Qwen/qwen35-6992e3053c019221cf2d725f'},
      {label: "Wikipédia, Qwen (Qwen3.5 publié en février 2026 ; billet « Qwen3.5: Towards Native Multimodal Agents » du 16 février 2026), consulté le 2 octobre 2026", url: 'https://en.wikipedia.org/wiki/Qwen'},
      {label: "Gu et Dao, Mamba: Linear-Time Sequence Modeling with Selective State Spaces, 1er décembre 2023 (paramètres de la couche fonctions du token lu ; « 5× higher throughput than Transformers »)", url: 'https://arxiv.org/abs/2312.00752'},
      {label: "Jelassi, Brandfonbrener, Kakade et Malach (Harvard), Repeat After Me: Transformers are Better than State Space Models at Copying, 1er février 2024 (annuaire synthétique, ligne type « John Powell: 609-3237777 » ; dès L ≥ 70 noms, le plus petit transformer, Pythia 410M, dépasse le plus gros Mamba, 2,8 milliards ; 2,8 / 0,41 = 6,8)", url: 'https://arxiv.org/abs/2402.01032'},
      {label: "Lieber et al. (AI21 Labs), Jamba: A Hybrid Transformer-Mamba Language Model, 28 mars 2024 (rapport attention / Mamba de 1 : 7 ; KV cache 8 fois plus petit qu'un transformer classique ; contexte de 256 000 tokens)", url: 'https://arxiv.org/abs/2403.19887'},
      {label: "Yang (MIT CSAIL), Kautz et Hatamizadeh (NVIDIA), Gated Delta Networks: Improving Mamba2 with Delta Rule, 9 décembre 2024, ICLR 2025", url: 'https://arxiv.org/abs/2412.06464'},
      {label: "Kimi Team (Moonshot AI), Kimi Linear: An Expressive, Efficient Attention Architecture, 30 octobre 2025 (rapport 3 : 1 entre KDA, variante de Gated DeltaNet, et attention complète ; jusqu'à 75 % de KV cache en moins et jusqu'à 6 fois le débit de décodage à 1 million de tokens)", url: 'https://arxiv.org/abs/2510.26692'},
      {label: "MiniMax, MiniMax-M1: Scaling Test-Time Compute Efficiently with Lightning Attention, 16 juin 2025 (« the world's first open-weight, large-scale hybrid-attention reasoning model »)", url: 'https://arxiv.org/abs/2506.13585'},
      {label: "MiniMax, Why Did M2 End Up as a Full Attention Model?, 30 octobre 2025 (« the model had clear deficits in complex, multi-hop reasoning tasks » ; « the benefits of linear and sparse attention will gradually emerge »)", url: 'https://huggingface.co/blog/MiniMax-AI/why-did-m2-end-up-as-a-full-attention-model'},
      {label: "IBM, IBM Granite 4.0: hyper-efficient, high performance hybrid models for enterprise, 2 octobre 2025 (Mamba-2 et transformer dans un rapport de 9 : 1 ; « over 70% reduction in RAM needed to handle long inputs and multiple concurrent batches »)", url: 'https://www.ibm.com/new/announcements/ibm-granite-4-0-hyper-efficient-high-performance-hybrid-models'},
    ],
  },
  {
    id: 'speculative-decoding',
    status: 'live',
    title: 'Décodage spéculatif',
    en: 'Speculative decoding',
    aliases: ['speculative decoding', 'speculative sampling', 'draft model', 'target model', 'multi-token prediction', 'MTP', 'EAGLE', 'Medusa', 'predicted outputs'],
    aliasesFr: ['décodage spéculatif', 'échantillonnage spéculatif', 'modèle brouillon'],
    jargon: [
      {say: 'draft model', means: "le modèle brouillon, petit et rapide, qui propose les prochains tokens ; le grand modèle qui les vérifie s'appelle le target model"},
      {say: 'acceptance rate', means: "la part des tokens proposés que le grand modèle garde ; c'est elle qui fait le gain de vitesse"},
      {say: 'MTP', means: "multi-token prediction, un petit module ajouté au modèle lui-même pour deviner le token d'après, ce qui évite d'entretenir un second modèle"},
      {say: 'Predicted Outputs', means: "chez OpenAI, une option où c'est le développeur qui fournit le brouillon, par exemple le fichier à modifier, que le modèle valide au lieu de le réécrire"},
    ],
    cat: 'inference',
    links: ['inference', 'logits', 'distillation', 'latence-vs-debit', 'cout-d-une-requete', 'prediction-du-mot-suivant'],
    short: "Le décodage spéculatif accélère un modèle en laissant un petit modèle deviner les prochains tokens, que le grand vérifie tous d'un seul passage, sans rien changer à la réponse.",
    image: "À côté du chanteur se tient désormais un choriste rapide qui lui souffle les quatre notes suivantes. Le chanteur les vérifie toutes d'un seul regard, garde celles qu'il aurait chantées lui-même et reprend la main à la première qui ne lui convient pas. Le choriste est le modèle brouillon, le chanteur le grand modèle, et l'image triche sur ce regard unique, puisque le modèle vérifie bien quatre tokens en un seul calcul, ce qu'aucun chanteur ne sait faire.",
    imagineForm: 'D',
    imagine: "Tu demandes « Quelle est la racine carrée de 7 ? ». « La racine carrée de 7 est 2,5 », souffle en une fraction de seconde le petit modèle, et le grand, qui relit ces mots d'un seul passage, garde « La racine carrée de 7 est » et remplace la fin par « 2,646 ».",
    full: [
      "Un modèle écrit sa réponse un token à la fois, et chaque token oblige le serveur à relire tous ses paramètres en mémoire pour très peu de calcul. Les chercheurs de Google à l'origine de la méthode notent que les puces savent faire des centaines d'opérations par octet lu, alors que le décodage n'en demande que quelques-unes, et que la puissance de calcul dort donc en bonne partie. Faire vérifier quatre ou cinq tokens d'un coup au grand modèle prend alors à peu près le temps qu'il lui faudrait pour en écrire un seul.",
      "En novembre 2022, Yaniv Leviathan, Matan Kalman et Yossi Matias décrivent le décodage spéculatif. Le petit modèle propose quelques tokens, le grand calcule d'un passage ses propres probabilités pour chacun, accepte ceux qu'il aurait pu écrire et tire lui-même le premier qu'il refuse, de sorte que la réponse suit exactement la même loi que s'il avait tout écrit seul. Avec T5-XXL, ils obtenaient des réponses identiques deux à trois fois plus vite, et DeepMind publiait la même idée en février 2023. Fin 2024, Google indiquait s'en servir pour les AI Overviews de son moteur de recherche.",
      "Le brouillon n'a plus besoin d'être un modèle à part. Dans DeepSeek-V3, publié en décembre 2024, un petit module greffé sur le modèle prédit le token d'après, que le modèle accepte dans 85 à 90 % des cas, et la vitesse d'écriture est multipliée par 1,8. Chez OpenAI, l'option Predicted Outputs laisse le développeur fournir lui-même le brouillon, comme un fichier de code dont seule une ligne doit changer, mais chaque token refusé reste facturé comme un token écrit.",
      "Le gain dépend de ce qui reste à deviner, et de la charge du serveur. Les mots faciles, comme ceux qui reprennent la question, se devinent bien, et un texte recopié avec quelques retouches se devine presque en entier, ce qui fait tout l'intérêt de l'option d'OpenAI. Quand le GPU sert déjà de nombreuses requêtes à la fois, la puissance inemployée qui rendait la vérification presque gratuite se fait rare, et EAGLE-3, une méthode publiée en mars 2025, ne gagnait plus que 38 % de débit avec des lots de 64 requêtes.",
    ],
    office: [
      {who: 'q', text: "Le fournisseur active le décodage spéculatif sur notre modèle. On doit refaire toutes nos évaluations de qualité ?"},
      {who: 'a', text: "Pas pour la méthode d'origine, qui garantit les mêmes réponses que le grand modèle seul, à condition que la variante choisie ne modifie pas le grand modèle lui-même, comme le fait Medusa-2. Mesure plutôt la vitesse sur tes propres textes, car elle varie avec ce que le brouillon arrive à deviner."},
    ],
    avoid: "« Avec le décodage spéculatif, c'est un petit modèle qui répond à la place du grand. » Chaque token de la réponse est validé par le grand modèle, qui garde le dernier mot ; un mauvais brouillon ralentit la réponse sans jamais changer le texte.",
    video: null,
    sources: [
      {label: "Leviathan, Kalman et Matias (Google Research), Looking back at speculative decoding, 6 décembre 2024 (exemple « What is the square root of 7? The square root of 7 is 2.646 », où « 7 » est facile à deviner et « 2.646 » difficile ; le matériel fait « hundreds of operations for every byte read » contre « only a few » pour un transformer en inférence ; utilisé dans les AI Overviews de Google Search). Les mots proposés par le petit modèle dans l'Imagine sont un exemple illustratif", url: 'https://research.google/blog/looking-back-at-speculative-decoding/'},
      {label: "Leviathan, Kalman et Matias (Google), Fast Inference from Transformers via Speculative Decoding, 30 novembre 2022 (« without any changes to the outputs » ; accélération de 2 à 3 fois sur T5-XXL, « with identical outputs »)", url: 'https://arxiv.org/abs/2211.17192'},
      {label: "Chen et al. (DeepMind), Accelerating Large Language Model Decoding with Speculative Sampling, 2 février 2023 (vérifier en parallèle une courte suite prend un temps comparable à l'écriture d'un token ; 2 à 2,5 fois plus rapide sur Chinchilla 70B)", url: 'https://arxiv.org/abs/2302.01318'},
      {label: "DeepSeek-AI, DeepSeek-V3 Technical Report, 27 décembre 2024, section 5.4.3 (taux d'acceptation du second token prédit par le module MTP entre 85 % et 90 % ; « 1.8 times TPS »)", url: 'https://arxiv.org/abs/2412.19437'},
      {label: "OpenAI, guide Predicted Outputs, consulté le 2 octobre 2026 (accélère les réponses quand une grande partie de la sortie est connue d'avance, comme un fichier de code légèrement modifié ; « any rejected tokens are still billed like other completion tokens »)", url: 'https://developers.openai.com/api/docs/guides/predicted-outputs'},
      {label: "Li et al., EAGLE-3: Scaling up Inference Acceleration of Large Language Models via Training-Time Test, 3 mars 2025 (jusqu'à 6,5 fois plus rapide ; « 1.38x throughput improvement at a batch size of 64 » dans SGLang)", url: 'https://arxiv.org/abs/2503.01840'},
      {label: "Cai et al., Medusa: Simple LLM Inference Acceleration Framework with Multiple Decoding Heads, 19 janvier 2024 (Medusa-1 sans perte sur un modèle figé ; Medusa-2 entraîné avec le modèle lui-même)", url: 'https://arxiv.org/abs/2401.10774'},
    ],
  },
  {
    id: 'latence-vs-debit',
    status: 'live',
    title: 'Latence et débit',
    en: 'Latency vs throughput',
    aliases: ['latency', 'throughput', 'latency vs throughput', 'TTFT', 'time to first token', 'tokens per second', 'TPS', 'inter-token latency', 'ITL', 'batching', 'continuous batching', 'service tier', 'fast mode', 'flex processing'],
    aliasesFr: ['latence', 'débit', 'temps de réponse', 'vitesse de génération'],
    jargon: [
      {say: 'TTFT', means: "time to first token, le délai entre l'envoi de ta requête et l'arrivée du premier token de la réponse"},
      {say: 'tokens/s', means: "tokens par seconde ; pour une personne, la vitesse à laquelle sa réponse s'écrit, pour un serveur, le total produit pour toutes les requêtes à la fois"},
      {say: 'batching', means: "le regroupement de nombreuses requêtes dans le même calcul sur le GPU, qui augmente le débit total et ralentit un peu chacune"},
      {say: 'service tier', means: "le palier de vitesse choisi dans la requête, comme flex, fast ou batch chez OpenAI, chacun avec son prix"},
    ],
    cat: 'inference',
    links: ['inference', 'kv-cache', 'gpu', 'cout-d-une-requete', 'speculative-decoding', 'architectures-hybrides'],
    short: "La latence mesure combien de temps tu attends ta réponse, le débit combien de tokens un serveur produit en tout, et servir plus de monde à la fois ralentit chacun.",
    image: "Loue la cabine à un seul groupe, et il repart vite avec sa prise ; fais-y passer dix groupes qui se relaient au micro, et chacun attend plus longtemps la sienne, pendant que le studio sort bien plus de morceaux dans la journée. La latence est l'attente de chaque groupe et le débit le nombre de morceaux sortis. L'image triche sur le relais, puisqu'un GPU fait avancer toutes les requêtes ensemble, d'un token chacune à chaque pas.",
    imagineForm: 'B',
    imagine: "Ouvre ton chatbot habituel, lance le chronomètre de ton téléphone et demande-lui un résumé de 300 mots de ton film préféré. Note le temps qui passe avant le premier mot, puis la durée jusqu'au dernier, et divise 300 par cette seconde durée pour obtenir ses mots par seconde. Refais l'essai en activant la réflexion approfondie, et regarde surtout l'attente du premier mot de la réponse s'allonger.",
    full: [
      "Une réponse se mesure en deux temps. Le délai avant le premier token, le TTFT (time to first token), couvre surtout la lecture de ton message, puis vient la vitesse d'écriture, qui dépend du temps entre deux tokens. NVIDIA conseille de garder le premier sous 250 millisecondes pour qu'une conversation paraisse réactive. Un modèle de raisonnement déplace l'attente, puisqu'il écrit son brouillon avant la réponse visible, et le premier mot que tu lis arrive d'autant plus tard.",
      "Le débit, lui aussi compté en tokens par seconde, additionne ce que le serveur produit pour tout le monde. Un GPU qui écrit pour une seule personne relit tous les paramètres du modèle à chaque token et laisse dormir l'essentiel de sa puissance, alors que s'il traite des dizaines de requêtes ensemble, la même lecture les fait toutes avancer. NVIDIA le constate dans ses mesures, où le débit total du système grimpe avec le nombre de requêtes simultanées pendant que celui de chaque utilisateur baisse. Le KV cache de chaque conversation occupe la mémoire du GPU et borne le nombre de places.",
      "Les fournisseurs vendent désormais ce compromis à la carte, et le tableau ci-dessous en donne les prix. Chez OpenAI, GPT-6 Astra existe en cinq vitesses, du traitement par lots rendu sous 24 heures à moitié prix jusqu'à l'Ultrafast, six fois plus cher que le tarif standard. Chez Anthropic, le fast mode de Claude Opus 5.5 double le prix pour écrire jusqu'à 2,5 fois plus de tokens par seconde avec les mêmes paramètres, sans raccourcir l'attente du premier token.",
      "L'autre voie consiste à changer de machine ou de modèle. En février 2026, OpenAI a lancé GPT-5.3-Codex-Spark, une version réduite de son modèle de code, servie sur les puces géantes de Cerebras à plus de 1 000 tokens par seconde pour retoucher du code en direct. Le décodage spéculatif et les architectures hybrides cherchent le même gain sans quitter le modèle d'origine.",
    ],
    table: {
      caption: "Prix d'un même modèle selon la vitesse",
      asOf: '2 octobre 2026',
      columns: ['Modèle et palier', 'Entrée $ / 1M tokens', 'Sortie $ / 1M tokens', 'Contrepartie'],
      rows: [
        ['GPT-6 Astra, Batch', '5', '25', 'résultat sous 24 heures'],
        ['GPT-6 Astra, Flex', '5', '25', 'réponses plus lentes, capacité parfois indisponible'],
        ['GPT-6 Astra, Standard', '10', '50', 'tarif de référence'],
        ['GPT-6 Astra, Fast', '20', '100', "jusqu'à 2,5 fois plus rapide"],
        ['GPT-6 Astra, Ultrafast', '60', '300', "le palier le plus rapide de l'API"],
        ['Claude Opus 5.5, Batch', '2', '10', 'résultat en général sous une heure, 24 heures au plus'],
        ['Claude Opus 5.5, Standard', '4', '20', 'tarif de référence'],
        ['Claude Opus 5.5, Fast', '8', '40', "jusqu'à 2,5 fois plus de tokens par seconde"],
      ],
      note: "Tarifs pour les requêtes de 272 000 tokens d'entrée au plus chez OpenAI.",
    },
    office: [
      {who: 'q', text: "On passe notre assistant client en fast mode, ça va régler les plaintes sur la lenteur ?"},
      {who: 'a', text: "Seulement si les clients se plaignent d'une réponse qui s'écrit lentement. Si c'est le premier mot qui tarde, cherche du côté de la longueur du contexte envoyé et du temps de réflexion, puisque le fast mode d'Anthropic accélère l'écriture et non le délai du premier token."},
    ],
    avoid: "« Ce fournisseur annonce 3 000 tokens par seconde, il répondra plus vite à nos clients. » Un chiffre de débit additionne souvent toutes les requêtes d'un serveur ; demande la vitesse par utilisateur et le délai avant le premier token, mesurés avec des requêtes de la longueur des tiennes.",
    video: null,
    sources: [
      {label: "NVIDIA, LLM Inference Benchmarking: Fundamental Concepts, 2 avril 2025 (définitions du TTFT, de la latence entre tokens, du débit par utilisateur et du débit du système ; « As the number of concurrent requests increases in the system, the total TPS for the whole system will increase, while TPS per user decreases as latency increases »)", url: 'https://developer.nvidia.com/blog/llm-benchmarking-fundamental-concepts'},
      {label: "NVIDIA, LLM Inference Benchmarking: How Much Does Your LLM Inference Cost?, 18 juin 2025 (« For chat applications with live interactive responses, keep the average time to first token at or below 250 ms » ; choisir le point de fonctionnement au débit le plus haut qui respecte la contrainte de latence)", url: 'https://developer.nvidia.com/blog/llm-inference-benchmarking-how-much-does-your-llm-inference-cost'},
      {label: "Leviathan, Kalman et Matias (Google Research), Looking back at speculative decoding, 6 décembre 2024 (en inférence, un transformer fait peu d'opérations par octet lu en mémoire, ce qui laisse de la puissance de calcul inemployée)", url: 'https://research.google/blog/looking-back-at-speculative-decoding/'},
      {label: "OpenAI, page des prix de l'API, consultée le 2 octobre 2026 (GPT-6 Astra par million de tokens, entrée et sortie : Standard 10 et 50 $, Batch et Flex 5 et 25 $, Fast 20 et 100 $, Ultrafast 60 et 300 $ ; « Short context: ≤272K input tokens » ; « Priority processing was renamed Fast mode on July 30, 2026 »). Calcul : 300 / 50 = 6", url: 'https://developers.openai.com/api/docs/pricing'},
      {label: "OpenAI, guide Batch API, consulté le 2 octobre 2026 (50 % de remise, chaque lot rendu sous 24 heures)", url: 'https://developers.openai.com/api/docs/guides/batch'},
      {label: "OpenAI, guide Flex processing, consulté le 2 octobre 2026 (prix du Batch « in exchange for slower response times and occasional resource unavailability »)", url: 'https://developers.openai.com/api/docs/guides/flex-processing'},
      {label: "OpenAI, guide Fast mode, consulté le 2 octobre 2026 (« up to 2.5× faster speeds and more consistent latency »)", url: 'https://developers.openai.com/api/docs/guides/priority-processing'},
      {label: "OpenAI, guide Ultrafast mode, consulté le 2 octobre 2026 (« Ultrafast mode is the fastest service tier in the OpenAI API », disponible pour GPT-6 Astra)", url: 'https://developers.openai.com/api/docs/guides/ultrafast-mode'},
      {label: "Anthropic, page des prix, consultée le 2 octobre 2026 (Claude Opus 5.5 par million de tokens : 4 $ en entrée et 20 $ en sortie ; Batch 2 et 10 $ ; fast mode 8 et 40 $)", url: 'https://platform.claude.com/docs/en/about-claude/pricing'},
      {label: "Anthropic, documentation Fast mode, consultée le 2 octobre 2026 (« Up to 2.5x higher output tokens per second » ; « Same model weights and behavior » ; « Speed benefits are focused on output tokens per second (OTPS), not time to first token (TTFT) »)", url: 'https://platform.claude.com/docs/en/build-with-claude/fast-mode'},
      {label: "Anthropic, documentation Batch processing, consultée le 2 octobre 2026 (la plupart des lots terminés en moins d'une heure, expiration au bout de 24 heures ; 50 % du prix standard)", url: 'https://platform.claude.com/docs/en/build-with-claude/batch-processing'},
      {label: "Cerebras, OpenAI GPT-5.3-Codex-Spark Powered by Cerebras, 12 février 2026 (« runs at over 1,000 tokens/s » ; « a smaller version of Codex optimized for fast inference »)", url: 'https://www.cerebras.ai/blog/openai-codexspark'},
    ],
  },
  {
    id: 'sortie-structuree',
    status: 'live',
    title: 'Sortie structurée',
    en: 'Structured output',
    aliases: ['structured output', 'structured outputs', 'JSON mode', 'JSON schema', 'constrained decoding', 'grammar-constrained decoding', 'guided generation', 'strict mode', 'response_format'],
    aliasesFr: ['sortie structurée', 'décodage contraint', 'mode JSON', 'génération guidée'],
    jargon: [
      {say: 'JSON Schema', means: "le format standard qui décrit les champs attendus, leur type et ceux qui sont obligatoires ; c'est lui qu'on donne au modèle comme moule"},
      {say: 'JSON mode', means: "l'option qui garantit un JSON valide, sans garantir qu'il contienne les champs voulus"},
      {say: 'constrained decoding', means: "le décodage contraint, qui écarte à chaque pas les tokens qui sortiraient du format, si bien que le modèle ne peut tirer qu'un token permis"},
      {say: 'strict', means: "chez OpenAI et Anthropic, le réglage qui applique le décodage contraint aux paramètres des appels d'outils"},
    ],
    cat: 'agents',
    links: ['logits', 'harness', 'system-prompt', 'agent', 'evals', 'prompt-engineering'],
    solutions: [
      {name: 'Structured Outputs (OpenAI)', kind: 'API', url: 'https://developers.openai.com/api/docs/guides/structured-outputs'},
      {name: 'Structured outputs (Anthropic)', kind: 'API', url: 'https://platform.claude.com/docs/en/build-with-claude/structured-outputs'},
      {name: 'Outlines', kind: 'bibliothèque open source', url: 'https://dottxt-ai.github.io/outlines/latest/'},
      {name: 'XGrammar', kind: 'bibliothèque open source', url: 'https://xgrammar.mlc.ai/'},
      {name: 'Instructor', kind: 'bibliothèque open source', url: 'https://python.useinstructor.com/'},
      {name: 'Pydantic', kind: 'validation de schéma', url: 'https://docs.pydantic.dev/latest/'},
    ],
    short: "Une sortie structurée est une réponse qu'un modèle doit rendre dans un format fixé d'avance, souvent un JSON conforme à un schéma, pour qu'un programme la lise sans erreur.",
    image: "Devant le micro, une grille à cases attend le chanteur, qui doit loger chaque note dans la case prévue, et la console coupe le son dès qu'une note en sortirait. La grille est le schéma, la coupure du son le décodage contraint. L'image triche sur cette coupure, puisque le modèle n'est jamais interrompu et que les tokens interdits sont rayés de la liste avant chaque tirage.",
    imagineForm: 'D',
    imagine: "« Classe ce ticket en facturation, livraison ou autre, et réponds uniquement en JSON », demande ton script au modèle. « Avec plaisir ! Ce ticket concerne la livraison, voici le JSON correspondant, et je peux ajouter le niveau d'urgence si tu le souhaites », répond le modèle, juste avant l'objet demandé.",
    full: [
      "Un programme qui lit la réponse d'un modèle attend un format exact, par exemple un objet JSON avec les bons champs, et une phrase de politesse en tête suffit à le faire planter. Réclamer le format dans la consigne marche souvent, sans garantie. OpenAI a d'abord proposé un mode JSON, qui assure un JSON valide sans assurer les champs. Sa documentation prévient qu'il faut quand même demander du JSON en toutes lettres, faute de quoi le modèle peut produire un flot d'espaces sans fin jusqu'à la limite de tokens.",
      "La vraie garantie vient du décodage contraint. Le schéma demandé est traduit en grammaire, et avant chaque token, le serveur retire des logits tous les tokens qui la violeraient, si bien que le modèle ne peut tirer qu'un token permis. En juillet 2023, Brandon Willard et Rémi Louf ont décrit une manière rapide de le faire dans la bibliothèque open source Outlines, et XGrammar, en novembre 2024, en a ramené le surcoût presque à zéro. Anthropic a ouvert le sien à ses clients en novembre 2025, et sa documentation précise que la première requête avec un nouveau schéma attend que la grammaire soit compilée, puis la garde 24 heures en cache.",
      "Le format garanti ne garantit pas le contenu. OpenAI prévient que les sorties structurées peuvent encore contenir des erreurs, et qu'un modèle forcé de remplir un schéma sans rapport avec le texte reçu peut inventer de quoi le remplir. Anthropic liste les cas où le schéma lui-même cède, un refus pour raison de sécurité, une réponse coupée par la limite de tokens, ou une valeur d'une liste fermée rendue avec une majuscule de trop. En août 2024, l'étude « Let Me Speak Freely? » mesurait aussi une nette baisse du raisonnement quand le format était imposé, d'autant plus forte que la contrainte était stricte.",
      "Le schéma se rédige donc comme une consigne. Les champs sortent dans l'ordre où il les déclare, et la documentation d'Anthropic avertit qu'un champ qui réclame le raisonnement pas à pas peut provoquer un refus, en conseillant de demander à la place une courte explication.",
    ],
    office: [
      {who: 'q', text: "Le JSON est garanti, alors on branche la sortie directement sur la base clients ?"},
      {who: 'a', text: "Sa forme l'est, pas ses valeurs. Garde une validation métier derrière, un numéro de client qui existe, un montant plausible, et essaie quelques documents qui n'ont rien à voir avec le schéma pour voir ce que le modèle invente quand il n'a rien à extraire."},
    ],
    avoid: "« J'ai activé le mode JSON, donc la réponse respecte mon schéma. » Le mode JSON ne garantit qu'un JSON valide ; seul le décodage contraint par un schéma garantit les champs, et même lui ne vérifie pas que les valeurs sont justes.",
    video: null,
    sources: [
      {label: "OpenAI, guide Structured model outputs, consulté le 2 octobre 2026 (JSON mode assure un JSON valide, Structured Outputs l'adhésion au schéma ; sans consigne explicite, en JSON mode, « the model may generate an unending stream of whitespace » ; « Structured Outputs can still contain mistakes » ; « can result in hallucinations if the input is completely unrelated to the schema » ; sortie dans l'ordre des clés du schéma)", url: 'https://developers.openai.com/api/docs/guides/structured-outputs'},
      {label: "Anthropic, documentation Structured outputs, consultée le 2 octobre 2026 (garantie par « constrained decoding » ; grammaire compilée à la première requête puis gardée 24 heures en cache ; sorties non conformes en cas de refus ou de max_tokens ; casse des valeurs enum non garantie ; un champ qui demande le raisonnement pas à pas peut provoquer un refus « reasoning_extraction », demander plutôt une courte explication)", url: 'https://platform.claude.com/docs/en/build-with-claude/structured-outputs'},
      {label: "Anthropic, Structured outputs on the Claude Developer Platform, 14 novembre 2025 (bêta publique pour Claude Sonnet 4.5 et Opus 4.1, disponibilité générale le 4 février 2026)", url: 'https://claude.com/blog/structured-outputs-on-the-claude-developer-platform'},
      {label: "Willard et Louf, Efficient Guided Generation for Large Language Models, 19 juillet 2023 (génération guidée par expressions régulières et grammaires, implémentée dans la bibliothèque Outlines)", url: 'https://arxiv.org/abs/2307.09702'},
      {label: "Dong et al., XGrammar: Flexible and Efficient Structured Generation Engine for Large Language Models, 22 novembre 2024 (jusqu'à 100 fois plus rapide que les solutions existantes, « near-zero overhead » de bout en bout)", url: 'https://arxiv.org/abs/2411.15100'},
      {label: "Tam et al., Let Me Speak Freely? A Study on the Impact of Format Restrictions on Performance of Large Language Models, 5 août 2024 (« a significant decline in LLMs reasoning abilities under format restrictions », plus forte quand la contrainte est stricte)", url: 'https://arxiv.org/abs/2408.02442'},
    ],
  },
];
