// Lexique IA, vague 9, lot T (technique). Format identique à lexique/terms.js, sans `num`.
// imagineForm : forme de l'« Imagine » (content/dico/univers.md, section « Les formes de l'Imagine »).
// Faits et chiffres relevés le 2 octobre 2026 sur les pages citées dans `sources`.
module.exports = [
  {
    id: 'position',
    status: 'live',
    title: 'Encodage positionnel',
    en: 'Positional encoding',
    aliases: ['positional encoding', 'positional embedding', 'position embedding', 'RoPE', 'rotary position embedding', 'ALiBi', 'NoPE', 'YaRN', 'context extension'],
    aliasesFr: ['encodage de position', 'position des tokens', 'extension de contexte'],
    jargon: [
      {say: 'RoPE', means: "rotary position embedding, la méthode publiée en avril 2021 qui code la place d'un token en faisant tourner ses vecteurs d'un angle qui grandit avec sa position"},
      {say: 'rope_theta', means: "le réglage, dans la configuration d'un modèle, qui fixe la vitesse de l'aiguille la plus lente de RoPE ; il vaut 1 000 000 chez Qwen3"},
      {say: 'YaRN', means: "Yet another RoPE extensioN, une recette d'août 2023 pour faire lire à un modèle des textes plus longs que ceux de son entraînement"},
      {say: 'NoPE', means: "no positional encoding, des couches d'attention qui ne reçoivent aucune information de position, comme une partie de celles de Llama 4"},
    ],
    cat: 'fondations',
    links: ['auto-attention', 'transformer', 'embedding', 'kv-cache', 'mythe-lit-mot-par-mot', 'architectures-hybrides'],
    short: "L'encodage positionnel est l'information qu'un transformer ajoute à chaque token pour indiquer sa place dans le texte, parce que l'attention, seule, ne voit pas l'ordre des mots.",
    image: "Verse sur la table de mixage tous les samples d'un morceau sans leur minutage, et personne au studio ne saurait plus dire si le refrain venait avant ou après le couplet. L'encodage positionnel est le timecode gravé sur chaque sample, qui lui rend sa place dans le morceau. L'image triche sur la forme de ce timecode, qui n'est pas un numéro qu'on lit mais une série d'angles, et le modèle s'en sert surtout pour mesurer l'écart entre deux samples.",
    imagineForm: 'A',
    imagine: "Dans Qwen3-8B, publié par Alibaba en avril 2025, la place de chaque token est codée par 64 aiguilles qui tournent chacune à sa vitesse, d'un cran à chaque token. Si le modèle lisait un token par seconde, la plus rapide ferait un tour toutes les 6,3 secondes et la plus lente un tour en 58 jours et demi. Sur toute la fenêtre native du modèle, 32 768 tokens, soit neuf heures de lecture, cette dernière aiguille n'avance que de 2 degrés.",
    full: [
      "L'auto-attention compare chaque token aux autres sans rien savoir de leur place, et sans autre indice « le chien mord le facteur » et « le facteur mord le chien » lui apporteraient les mêmes mots. Les auteurs du transformer posent le problème dès juin 2017, en notant que leur modèle, sans récurrence ni convolution, doit recevoir de l'extérieur la position des tokens. Ils ajoutent à l'embedding de chaque token une signature faite d'ondes de longueurs différentes, de 2π à 10 000 fois 2π positions, et constatent qu'une version apprise donne des résultats presque identiques.",
      "La version apprise a pourtant une limite très concrète. GPT-2 apprenait une ligne de table par position, 1 024 en tout, et un 1 025e token n'y aurait trouvé aucune ligne. En avril 2021, Jianlin Su et ses coauteurs publient RoPE, qui fait tourner les vecteurs comparés par l'attention d'un angle proportionnel à leur place, si bien que le score entre deux tokens ne dépend plus que de leur écart. Ce sont ses aiguilles qui tournent dans Qwen3. ALiBi, publié en août de la même année, retire des points au score à mesure que la distance grandit, et un modèle entraîné sur 1 024 tokens en lisait ainsi 2 048.",
      "Une position jamais vue pendant l'entraînement désoriente le modèle, et l'allongement des fenêtres passe par là. En juin 2023, des chercheurs de Meta ont porté la fenêtre de LLaMA à 32 768 tokens en moins de 1 000 pas d'entraînement, en resserrant les positions pour qu'elles retombent dans la plage connue au lieu de laisser les aiguilles tourner vers des angles inédits. YaRN, publié en août, affine cette recette, et Qwen3 s'en sert pour passer de 32 768 à 131 072 tokens.",
      "En avril 2025, Meta a même retiré tout encodage de position d'une partie des couches de Llama 4, une architecture qu'il appelle iRoPE, pour viser une fenêtre de 10 millions de tokens avec Llama 4 Scout. L'idée s'appuie sur une étude de mars 2022, selon laquelle un modèle qui ne regarde que les tokens précédents finit par déduire leur place sans aide, en somme en comptant combien il en a derrière lui.",
    ],
    office: [
      {who: 'q', text: "Notre Qwen3 installé en interne annonce 32 768 tokens. On peut lui confier un dossier de 100 000 ?"},
      {who: 'a', text: "Oui, en activant YaRN avec un facteur 4, qui le mène à 131 072 tokens. Alibaba conseille toutefois de ne pas le laisser allumé si tes textes restent sous les 32 768 tokens, car la version courante, à facteur fixe, peut dégrader les réponses sur les textes courts."},
    ],
    avoid: "« Le modèle sait où est chaque mot parce qu'il lit la phrase dans l'ordre. » Le transformer traite tous les tokens en même temps, et c'est l'encodage positionnel, ajouté à l'entrée ou appliqué dans chaque calcul d'attention, qui lui fournit l'ordre ; sans lui, il ne reste que le masque qui cache les tokens suivants pour laisser deviner une place.",
    video: null,
    sources: [
      {label: "Qwen, fichier config.json de Qwen3-8B sur Hugging Face (head_dim 128, rope_theta 1000000), consulté le 2 octobre 2026. Calcul de l'Imagine : 128 / 2 = 64 fréquences ; la plus rapide tourne d'un radian par token, soit un tour en 2π = 6,28 tokens ; la plus lente vaut 1 000 000^(-126/128) radian par token, soit un tour en 5 063 256 tokens, 58,6 jours à un token par seconde ; sur 32 768 tokens (9,1 heures), elle tourne de 360 × 32 768 / 5 063 256 = 2,3 degrés", url: 'https://huggingface.co/Qwen/Qwen3-8B/blob/main/config.json'},
      {label: "Qwen, fiche de Qwen3-8B sur Hugging Face, consultée le 2 octobre 2026 (32 768 tokens en natif, 131 072 avec YaRN, facteur 4 ; YaRN statique « potentially impacting performance on shorter texts », à n'activer que pour les longs contextes)", url: 'https://huggingface.co/Qwen/Qwen3-8B'},
      {label: "Wikipédia, Qwen (famille Qwen3 publiée le 28 avril 2025), consulté le 2 octobre 2026", url: 'https://en.wikipedia.org/wiki/Qwen'},
      {label: "Vaswani et al. (Google), Attention Is All You Need, juin 2017, section 3.5 (« Since our model contains no recurrence and no convolution... we must inject some information about the relative or absolute position » ; longueurs d'onde de 2π à 10000 · 2π ; version apprise aux résultats « nearly identical »)", url: 'https://arxiv.org/abs/1706.03762'},
      {label: "OpenAI, fichier config.json de GPT-2 sur Hugging Face (n_positions 1024), consulté le 2 octobre 2026 ; dans l'implémentation de Hugging Face, la position passe par une table apprise de cette taille (nn.Embedding(config.max_position_embeddings, ...))", url: 'https://huggingface.co/openai-community/gpt2/blob/main/config.json'},
      {label: "Su et al., RoFormer: Enhanced Transformer with Rotary Position Embedding, 20 avril 2021 (RoPE code la position absolue par une rotation et fait apparaître la position relative dans l'attention)", url: 'https://arxiv.org/abs/2104.09864'},
      {label: "Press, Smith et Lewis, Train Short, Test Long: Attention with Linear Biases Enables Input Length Extrapolation, 27 août 2021 (ALiBi pénalise le score d'attention proportionnellement à la distance ; entraîné sur 1 024 tokens, extrapole à 2 048)", url: 'https://arxiv.org/abs/2108.12409'},
      {label: "Chen et al. (Meta), Extending Context Window of Large Language Models via Positional Interpolation, 27 juin 2023 (LLaMA étendu jusqu'à 32 768 tokens en moins de 1 000 pas, positions réduites pour rester dans la fenêtre d'origine)", url: 'https://arxiv.org/abs/2306.15595'},
      {label: "Peng et al., YaRN: Efficient Context Window Extension of Large Language Models, 31 août 2023", url: 'https://arxiv.org/abs/2309.00071'},
      {label: "Meta, The Llama 4 herd, 5 avril 2025 (« interleaved attention layers without positional embeddings », architecture iRoPE ; Llama 4 Scout passe de 128 000 tokens chez Llama 3 à 10 millions)", url: 'https://ai.meta.com/blog/llama-4-multimodal-intelligence/'},
      {label: "Haviv et al., Transformer Language Models without Positional Encodings Still Learn Positional Information, 30 mars 2022 (sans encodage, un modèle causal acquiert une notion implicite de position absolue, sans doute en comptant les tokens qui le précèdent)", url: 'https://arxiv.org/abs/2203.16634'},
    ],
  },
  {
    id: 'architectures-hybrides',
    status: 'live',
    title: 'Architectures hybrides',
    en: 'Hybrid architectures',
    aliases: ['hybrid architecture', 'hybrid model', 'hybrid attention', 'linear attention', 'state space model', 'SSM', 'Mamba', 'Gated DeltaNet', 'Jamba', 'Kimi Linear'],
    aliasesFr: ['modèle hybride', 'attention hybride', 'attention linéaire', "modèle à espace d'états"],
    jargon: [
      {say: 'SSM', means: "state space model, modèle à espace d'états, une famille de couches récurrentes dont Mamba est la plus connue"},
      {say: 'linear attention', means: "l'attention linéaire, dont le coût grandit comme la longueur du texte et non comme son carré, parce qu'elle tient un résumé au lieu de tout relire"},
      {say: 'Gated DeltaNet', means: "la couche récurrente présentée en décembre 2024 par des chercheurs du MIT et de NVIDIA, qui efface ou corrige sa mémoire de façon ciblée ; c'est celle de Qwen3.5"},
      {say: '3:1', means: "trois couches récurrentes pour une couche d'attention complète, le dosage de Kimi Linear et de Qwen3.5"},
    ],
    cat: 'fondations',
    links: ['transformer', 'auto-attention', 'moe', 'position', 'fenetre-de-contexte', 'latence-vs-debit'],
    short: "Une architecture hybride mêle dans un même modèle des couches d'attention, qui relisent tout le texte, et des couches récurrentes, qui le résument dans une mémoire de taille fixe.",
    image: "Trois musiciens sur quatre jouent désormais de mémoire, avec pour seule aide un carnet de taille fixe qu'ils raturent et complètent à chaque mesure, et le quatrième garde toute la bande dans son casque pour retrouver une note précise jouée une heure plus tôt. L'architecture hybride organise ce partage entre couches récurrentes et couches d'attention. L'image triche sur le carnet, qui ne contient pas de notes lisibles mais un tableau de nombres remanié à chaque token.",
    imagineForm: 'D',
    imagine: "« Le dossier remplit les 262 144 tokens de la fenêtre ; combien de mémoire faut-il aux 45 couches Gated DeltaNet de Qwen3.5 pour le garder ? », demande une développeuse à son équipe. « Environ 190 Mo, autant que pour une seule phrase, et c'est aux 15 couches d'attention qu'il faut 8 Go de cache. »",
    full: [
      "L'attention complète a un défaut qui grandit avec le texte, puisque chaque token se compare à tous ceux qui le précèdent et que le KV cache s'allonge à chaque token. Les couches récurrentes reprennent l'idée des réseaux d'avant 2017, qui résumaient leur lecture au fil de l'eau dans une mémoire, l'état, dont la taille ne change pas, qu'on ait lu dix tokens ou un million. En décembre 2023, Albert Gu et Tri Dao publient Mamba, une couche de ce type qui choisit ce qu'elle garde selon le token lu, avec un débit annoncé cinq fois supérieur à celui d'un transformer.",
      "Ce résumé se paie en détails. En février 2024, des chercheurs de Harvard donnent à des modèles pré-entraînés un annuaire inventé, aux lignes du type « John Powell: 609-3237777 », puis demandent le numéro d'un nom tiré au hasard. Dès 70 noms, le plus petit transformer testé, 410 millions de paramètres, fait mieux que le plus gros Mamba, près de sept fois plus grand, parce que l'annuaire ne tient plus dans son état.",
      "D'où l'idée de garder un peu d'attention pour retrouver les détails et de confier le reste à des couches récurrentes. Jamba, sorti par AI21 Labs en mars 2024, place une couche d'attention pour sept couches Mamba et divise par huit son KV cache. En octobre 2025, Moonshot AI publie Kimi Linear, trois couches récurrentes pour une d'attention, avec jusqu'à 75 % de cache en moins et un décodage jusqu'à six fois plus rapide sur un million de tokens.",
      "Tout le monde n'en est pas convaincu. MiniMax avait bâti M1, en juin 2025, sur une attention hybride, puis est revenu à l'attention complète pour M2. Ses ingénieurs ont expliqué fin octobre 2025 que la version hybride, à grande échelle, montrait de nets déficits sur le raisonnement en plusieurs étapes, tout en prédisant que l'attention économe finira par s'imposer à mesure que les textes s'allongent plus vite que la puissance des GPU.",
    ],
    then: "En 2024, Jamba faisait figure d'exception parmi des modèles presque tous bâtis sur l'attention complète. En février 2026, Alibaba passe toute sa famille Qwen3.5 à l'architecture hybride, de la version de 0,8 milliard de paramètres à celle de 397 milliards, avec une couche d'attention pour trois couches Gated DeltaNet.",
    office: [
      {who: 'q', text: "Un modèle hybride, ça change quoi pour notre agent qui lit des dépôts de code entiers ?"},
      {who: 'a', text: "Surtout la mémoire et la vitesse quand le contexte s'allonge, et IBM annonce plus de 70 % de mémoire en moins sur les longs textes avec Granite 4.0. Vérifie quand même sur tes propres dépôts qu'il retrouve un détail précis enfoui au milieu, puisque c'est là que les couches récurrentes cèdent les premières."},
    ],
    avoid: "« Mamba a remplacé le transformer. » Jamba, Kimi Linear et Qwen3.5 gardent tous des couches d'attention complète, d'une sur huit à une sur quatre, justement pour retrouver les détails que la mémoire de taille fixe laisse filer ; MiniMax est même revenu à l'attention complète pour M2.",
    video: null,
    sources: [
      {label: "Qwen, fichier config.json de Qwen3.5-397B-A17B sur Hugging Face, consulté le 2 octobre 2026 (60 couches, dont 45 linear_attention et 15 full_attention ; 2 têtes de clés et valeurs de 256 dimensions ; 64 têtes Gated DeltaNet de 128 × 128 ; état en float32 ; fenêtre de 262 144 tokens). Calculs de l'Imagine : cache des 15 couches d'attention = 15 × 2 × 2 × 256 × 2 octets = 30 720 octets par token, soit 8,05 Go à 262 144 tokens ; état des 45 couches = 45 × 64 × 128 × 128 × 4 octets = 189 Mo, quelle que soit la longueur", url: 'https://huggingface.co/Qwen/Qwen3.5-397B-A17B/blob/main/config.json'},
      {label: "Qwen, fiche de Qwen3.5-397B-A17B sur Hugging Face, consultée le 2 octobre 2026 (« Hidden Layout: 15 * (3 * (Gated DeltaNet -> MoE) -> 1 * (Gated Attention -> MoE)) » ; 262 144 tokens en natif)", url: 'https://huggingface.co/Qwen/Qwen3.5-397B-A17B'},
      {label: "Qwen, collection Qwen3.5 sur Hugging Face, consultée le 2 octobre 2026 (de Qwen3.5-0.8B à Qwen3.5-397B-A17B ; les configurations de 0.8B, 27B, 122B-A10B et 397B-A17B ont toutes une couche full_attention pour trois linear_attention)", url: 'https://huggingface.co/collections/Qwen/qwen35-6992e3053c019221cf2d725f'},
      {label: "Wikipédia, Qwen (Qwen3.5 publié en février 2026 ; billet « Qwen3.5: Towards Native Multimodal Agents » du 16 février 2026), consulté le 2 octobre 2026", url: 'https://en.wikipedia.org/wiki/Qwen'},
      {label: "Gu et Dao, Mamba: Linear-Time Sequence Modeling with Selective State Spaces, 1er décembre 2023 (paramètres de la couche fonctions du token lu ; « 5× higher throughput than Transformers »)", url: 'https://arxiv.org/abs/2312.00752'},
      {label: "Jelassi, Brandfonbrener, Kakade et Malach (Harvard), Repeat After Me: Transformers are Better than State Space Models at Copying, 1er février 2024 (annuaire synthétique, ligne type « John Powell: 609-3237777 » ; dès L ≥ 70 noms, le plus petit transformer, Pythia 410M, dépasse le plus gros Mamba, 2,8 milliards ; 2,8 / 0,41 = 6,8)", url: 'https://arxiv.org/abs/2402.01032'},
      {label: "Lieber et al. (AI21 Labs), Jamba: A Hybrid Transformer-Mamba Language Model, 28 mars 2024 (rapport attention / Mamba de 1 : 7 ; KV cache 8 fois plus petit qu'un transformer classique ; contexte de 256 000 tokens)", url: 'https://arxiv.org/abs/2403.19887'},
      {label: "Yang (MIT CSAIL), Kautz et Hatamizadeh (NVIDIA), Gated Delta Networks: Improving Mamba2 with Delta Rule, 9 décembre 2024, ICLR 2025", url: 'https://arxiv.org/abs/2412.06464'},
      {label: "Kimi Team (Moonshot AI), Kimi Linear: An Expressive, Efficient Attention Architecture, 30 octobre 2025 (rapport 3 : 1 entre KDA, variante de Gated DeltaNet, et attention complète ; jusqu'à 75 % de KV cache en moins et jusqu'à 6 fois le débit de décodage à 1 million de tokens)", url: 'https://arxiv.org/abs/2510.26692'},
      {label: "MiniMax, MiniMax-M1: Scaling Test-Time Compute Efficiently with Lightning Attention, 16 juin 2025 (« the world's first open-weight, large-scale hybrid-attention reasoning model »)", url: 'https://arxiv.org/abs/2506.13585'},
      {label: "MiniMax, Why Did M2 End Up as a Full Attention Model?, 30 octobre 2025 (« the model had clear deficits in complex, multi-hop reasoning tasks » ; « the benefits of linear and sparse attention will gradually emerge »)", url: 'https://huggingface.co/blog/MiniMax-AI/why-did-m2-end-up-as-a-full-attention-model'},
      {label: "IBM, IBM Granite 4.0: hyper-efficient, high performance hybrid models for enterprise, 2 octobre 2025 (Mamba-2 et transformer dans un rapport de 9 : 1 ; « over 70% reduction in RAM needed to handle long inputs and multiple concurrent batches »)", url: 'https://www.ibm.com/new/announcements/ibm-granite-4-0-hyper-efficient-high-performance-hybrid-models'},
    ],
  },
];
